### ISSUE TITLE
Decide on what to do with `jaraco.*` projects

### ISSUE THREAD

**Issue by johnslavik** [coherent-oss/granary#2]
A number of projects lands in the `jaraco/` directory of `site-packages/` during installation:
|                                                                    |   downloads last month | jaraco's role   | uses skeleton?                                                        |
|:-------------------------------------------------------------------|-----------------------:|:----------------|:----------------------------------------------------------------------|
| [jaraco.classes](https://github.com/jaraco/jaraco.classes)         |               40009617 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.functools](https://github.com/jaraco/jaraco.functools)     |                1695144 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.collections](https://github.com/jaraco/jaraco.collections) |                 873666 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.text](https://github.com/jaraco/jaraco.text)               |                 855839 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.context](https://github.com/jaraco/jaraco.context)         |                 778832 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.logging](https://github.com/jaraco/jaraco.logging)         |                  34133 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.stream](https://github.com/jaraco/jaraco.stream)           |                  21597 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2021-informational) |
| [jaraco.itertools](https://github.com/jaraco/jaraco.itertools)     |                   7966 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.env](https://github.com/jaraco/jaraco.env)                 |                   6257 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.path](https://github.com/jaraco/jaraco.path)               |                   4119 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.envs](https://github.com/jaraco/jaraco.envs)               |                   3813 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.email](https://github.com/jaraco/jaraco.email)             |                   3717 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.versioning](https://github.com/jaraco/jaraco.versioning)   |                   3631 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.packaging](https://github.com/jaraco/jaraco.packaging)     |                   3562 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.abode](https://github.com/jaraco/jaraco.abode)             |                   3494 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.docker](https://github.com/jaraco/jaraco.docker)           |                   3134 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2022-informational) |
| [jaraco.ui](https://github.com/jaraco/jaraco.ui)                   |                   3123 | Owner           | ❌                                                                    |
| [jaraco.windows](https://github.com/jaraco/jaraco.windows)         |                   3024 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.structures](https://github.com/jaraco/jaraco.structures)   |                   2770 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.develop](https://github.com/jaraco/jaraco.develop)         |                   2470 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.net](https://github.com/jaraco/jaraco.net)                 |                   2259 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.vcs](https://github.com/jaraco/jaraco.vcs)                 |                   1989 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.mongodb](https://github.com/jaraco/jaraco.mongodb)         |                    758 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.services](https://github.com/jaraco/jaraco.services)       |                    430 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.clipboard](https://github.com/jaraco/jaraco.clipboard)     |                    379 | Owner           | ❌                                                                    |
| [jaraco.test](https://github.com/jaraco/jaraco.test)               |                    376 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2022-informational) |
| [jaraco.tidelift](https://github.com/jaraco/jaraco.tidelift)       |                    297 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.fabric](https://github.com/jaraco/jaraco.fabric)           |                    277 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.xonsh](https://github.com/jaraco/jaraco.xonsh)             |                    211 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.pmxbot](https://github.com/jaraco/jaraco.pmxbot)           |                    196 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.util](https://github.com/jaraco/jaraco.util)               |                    194 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2021-informational) |
| [jaraco.postgres](https://github.com/jaraco/jaraco.postgres)       |                    188 | Owner           | ❌                                                                    |
| [jaraco.financial](https://github.com/jaraco/jaraco.financial)     |                    153 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.apt](https://github.com/jaraco/jaraco.apt)                 |                    129 | Owner           | ❌                                                                    |
| [jaraco.timing](https://github.com/jaraco/jaraco.timing)           |                    124 | Owner           | ❌                                                                    |
| [jaraco.modb](https://github.com/jaraco/jaraco.modb)               |                    119 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.crypto](https://github.com/jaraco/jaraco.crypto)           |                    116 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.home](https://github.com/jaraco/jaraco.home)               |                    107 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.site](https://github.com/jaraco/jaraco.site)               |                     76 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.compat](https://github.com/jaraco/jaraco.compat)           |                     68 | Owner           | ❌                                                                    |
| [jaraco.nxt](https://github.com/jaraco/jaraco.nxt)                 |                     64 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.video](https://github.com/jaraco/jaraco.video)             |                     60 | Owner           | ❌                                                                    |
| [jaraco.media](https://github.com/jaraco/jaraco.media)             |                     54 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2022-informational) |
| [jaraco.geo](https://github.com/jaraco/jaraco.geo)                 |                     54 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.xkcd](https://github.com/jaraco/jaraco.xkcd)               |                     48 | Owner           | ❌                                                                    |
| [jaraco.zstd](https://github.com/jaraco/jaraco.zstd)               |                     42 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2023-informational) |
| [jaraco.translate](https://github.com/jaraco/jaraco.translate)     |                     34 | Owner           | ❌                                                                    |
| [jaraco.input](https://github.com/jaraco/jaraco.input)             |                     29 | Owner           | ❌                                                                    |
| [jaraco.keyring](https://github.com/jaraco/jaraco.keyring)         |                     28 | Owner           | ❌                                                                    |
| [jaraco.office](https://github.com/jaraco/jaraco.office)           |                     26 | Owner           | ❌                                                                    |
| [jaraco.imaging](https://github.com/jaraco/jaraco.imaging)         |                     23 | Owner           | ❌                                                                    |
| [jaraco.parables](https://github.com/jaraco/jaraco.parables)       |                     16 | Owner           | ❌                                                                    |

<sub>(Table generated with [`jaraco_namespace.py`](https://gist.github.com/bswck/5856bb0d46e46054f5faf3f4c953cda5)).</sub>

Should we (and how) change the namespace of these?
@jaraco

**Comment by johnslavik** [comment]
`jaraco.develop` and `jaraco.site` can be surely excluded from the list.
Assuming we migrate to `coherent.*`, some could be renamed on the way, e.g. `jaraco.envs`→`coherent.venvs` (a better distinction from `coherent.env`).
Some packages could be checked if they should be actually maintained by Coherent OSS, especially those that don't use skeleton or their last release was before 2023:

|                                                                    |   downloads last month | jaraco's role   | uses skeleton?                                                        |
|:-------------------------------------------------------------------|-----------------------:|:----------------|:----------------------------------------------------------------------|
| [jaraco.stream](https://github.com/jaraco/jaraco.stream)           |                  21597 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2021-informational) |
| [jaraco.docker](https://github.com/jaraco/jaraco.docker)           |                   3134 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2022-informational) |
| [jaraco.ui](https://github.com/jaraco/jaraco.ui)                   |                   3123 | Owner           | ❌                                                                    |
| [jaraco.clipboard](https://github.com/jaraco/jaraco.clipboard)     |                    379 | Owner           | ❌                                                                    |
| [jaraco.test](https://github.com/jaraco/jaraco.test)               |                    376 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2022-informational) |
| [jaraco.postgres](https://github.com/jaraco/jaraco.postgres)       |                    188 | Owner           | ❌                                                                    |
| [jaraco.apt](https://github.com/jaraco/jaraco.apt)                 |                    129 | Owner           | ❌                                                                    |
| [jaraco.timing](https://github.com/jaraco/jaraco.timing)           |                    124 | Owner           | ❌                                                                    |
| [jaraco.compat](https://github.com/jaraco/jaraco.compat)           |                     68 | Owner           | ❌                                                                    |
| [jaraco.video](https://github.com/jaraco/jaraco.video)             |                     60 | Owner           | ❌                                                                    |
| [jaraco.media](https://github.com/jaraco/jaraco.media)             |                     54 | Owner           | ![skeleton](https://img.shields.io/badge/skeleton-2022-informational) |
| [jaraco.xkcd](https://github.com/jaraco/jaraco.xkcd)               |                     48 | Owner           | ❌                                                                    |
| [jaraco.translate](https://github.com/jaraco/jaraco.translate)     |                     34 | Owner           | ❌                                                                    |
| [jaraco.input](https://github.com/jaraco/jaraco.input)             |                     29 | Owner           | ❌                                                                    |
| [jaraco.keyring](https://github.com/jaraco/jaraco.keyring)         |                     28 | Owner           | ❌                                                                    |
| [jaraco.office](https://github.com/jaraco/jaraco.office)           |                     26 | Owner           | ❌                                                                    |
| [jaraco.imaging](https://github.com/jaraco/jaraco.imaging)         |                     23 | Owner           | ❌                                                                    |
| [jaraco.parables](https://github.com/jaraco/jaraco.parables)       |                     16 | Owner           | ❌                                                                    |

For each of these, let's determine whether they are still going to be maintained or not.

**Comment by johnslavik** [comment]
`jaraco.stream`, `jaraco.docker` and `jaraco.ui` got quite a bit of downloads last month, so I guess Coherent OSS should continue maintaining it. As for the rest, I'm concerned the migration might be an unnecessary hassle.

**Comment by jaraco** [comment]
Hmm. I hadn't planned on renaming the projects or their namespace anytime soon. My instinct was to start with:

- Host the jaraco.* projects under coherent without rename.
- So, `jaraco/jaraco.collections` would move to `coherent-oss/jaraco.collections` and would still install `jaraco.collections`.

This approach would allow the projects to be maintained by the organization and benefit from the uniformity of settings that can be applied at the organization level (settings relating to auto-merge, etc) and simplify custodial matters relating to bus factor and collaboration.

I was not planning to migrate anything to `coherent.*` yet. I'd probably start by creating the next new thing under `coherent.*` but not migrate anything right away. I'd want to make sure the name has legs and doesn't run into any conflicts or disputes before forcing a transition on users and downstream packagers (I'm thinking about Linux package managers and my former Google colleagues and the toil they would endure simply by migrating half a dozen packages).

> For each of these, let's determine whether they are still going to be maintained or not.

My instinct is that anything that's likely to get a release anytime in the future should probably be migrated. Even if it's very personal (like jaraco.develop mostly is), it's still beneficial to share the custody of it, even if other members of coherent-oss would be largely uninterested in maintaining it. There would be no obligation to host it and the repo would likely get archived or turned down on my demise, but otherwise it would operate more or less as it had under my personal account.

There are maybe a handful of these that I might recommend for archival now (`jaraco.office`, `jaraco.geo`, `jaraco.compat` come to mind), and thus could be excluded, but I'd recommend if they're going to be excluded, let's archive them first and thus exclude archived repos from migration.

I'm genuinely surprised how many of those aren't using skeleton. My suspicion is that they are using skeleton, but I just haven't had the need or desire to cut a release. For example, [jaraco.parables](/jaraco/jaraco.parables) has been synced with skeleton 2024, but is so stable that it doesn't have a release in PyPI. It probably deserves a release in PyPI just to update the badge and other best practices. On the other hand, that library was extracted from pmxbot, so maybe it makes sense to migrate _it_ to the [pmxbot](/pmxbot) org (with or without a rename). Since I was looking at it, I cut a release just to give it a refresh.

All that said, I don't want to sully the name of coherent-oss by littering it with a bunch of junk. On the other hand, I do want the barrier to entry for any contribution to be incredibly low. `jaraco.docker` is [12 lines of code](https://github.com/jaraco/jaraco.docker/blob/main/jaraco/docker/__init__.py) that gives StackOverflow users an [easy answer](https://stackoverflow.com/a/49944991/70170) to a rather mundane but impactful question.

I'm happy to adjust to your expectations. Feel free to propose a different approach, but here's what I recommend:

- migrate everything that's maintained supported (unarchived)
- be prepared to migrate back anything that turns out to be a nuisance

Let me know what you think.

**Comment by johnslavik** [comment]
Thanks!

> I'm happy to adjust to your expectations. Feel free to propose a different approach, but here's what I recommend:
> 
> * migrate everything that's maintained supported (unarchived)
> * be prepared to migrate back anything that turns out to be a nuisance
> 
> Let me know what you think.

I really like that empirical approach, it will be the most optimal for your and my time.
As everything is clear now, I'll close this as completed and jump on #3.
